### PR TITLE
Fixed bug, alongside feedback implementations

### PR DESCRIPTION
**Pull request by sodiqsanusi**

### CODE REVIEW

**Comment by sodiqsanusi** [comment]
@fathermerry 

Implemented the feedback given. Also fixed the bug which caused the build process to fail.
I do not have access to the preview deployment, so I have little idea on how it looks in production. Do let me know of any other feedback you have on this

**Comment by fathermerry** [comment]
Feedback here: https://www.loom.com/share/a2504b02fc574ba8b7536873b3494764?sid=6f00c23b-a595-46cc-b3bb-5ef2392c6e86

**Comment by fathermerry** [comment]
@sodiqsanusi Any updates here?

**Comment by sodiqsanusi** [comment]
> @sodiqsanusi Any updates here?

Hi Ope. Yea, I've implemented the feedback you highlighted in the Loom Video. Waiting on some images from Samson which you said should be changed in the markdown.

Should I make a new PR with the current changes, since changing the images is something that could be done easily?

@fathermerry

**Comment by fathermerry** [comment]
Yes. Use Blank images (placeholder)

**Pull request closed without merging**
